before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - master
cache:
  - bundler
language:
  - ruby
notifications:
  campfire:
    on_failure:
      - always
    on_success:
      - change
    template:
      - '(%{branch} - %{author}): %{message} - %{build_url}'
  email:
    - false
rvm:
  - 2.1.3
addons:
  postgresql: "9.3"
