# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Rubrique.create(titre: 'NEWS', id: 1)
Rubrique.create(titre: 'DEPECHES', id:2)
Rubrique.create(titre: 'TOP VIDEOS', id:3)
Rubrique.create(titre: 'TOP ANNONCES', id: 4)
Rubrique.create(titre: 'BON A SAVOIR', id: 5)
Rubrique.create(titre: 'MOURIDE DE LA SEMAINE', id: 6)
Rubrique.create(titre: 'INFO EN CONTINU', id: 7)
Rubrique.create(titre: 'DECOUVERTES', id: 8)
Rubrique.create(titre: 'PUBLI-REPORTAGE & DOSSIERS', id: 9)
Rubrique.create(titre: 'CONTRIBUTIONS', id: 10)
Rubrique.create(titre: 'SAGESSE', id: 11)
Rubrique.create(titre: 'RETROVISEUR', id: 12)
Rubrique.create(titre: 'DOSSIER D''ACTUALITE', id: 13)
Rubrique.create(titre: 'ANNONCE', id: 14)
Rubrique.create(titre: 'PUB', id: 15)
Rubrique.create(titre: 'ALBUM A LA UNE', id: 16)
Rubrique.create(titre: 'VIDÉO DE LA SEMAINE', id: 17)
Rubrique.create(titre: 'ARCHIVES PLATEAUX MAGAL 1434 ', id: 18)
Rubrique.create(titre: 'PHOTO DE LA SEMAINE', id: 19)
Rubrique.create(titre: 'LIVE', id: 20)
Rubrique.create(titre: 'EVENEMENT', id: 21)
Rubrique.create(titre: 'Magal You-Tube TV', id: 22)
Rubrique.create(titre: 'Banniere magal 2014', id: 23 )
Rubrique.create(titre: 'Le Fondateur du Mouridisme', id: 24)
Rubrique.create(titre: 'Le Grand Magal de Touba', id: 25)
Rubrique.create(titre: 'La Ville Sainte de Touba', id: 26)
Rubrique.create(titre: 'Les Khalifs du Cheikh', id: 27)
Rubrique.create(titre: 'Le comite d''organisation', id: 28)
Rubrique.create(titre: 'La Grande Mosquée de Touba', id: 29)
Rubrique.create(titre: 'La Bibliothèque Cheikhoul Khadim', id: 30)
Rubrique.create(titre: 'Hotel de Ville de Touba', id: 31)
Rubrique.create(titre: 'La Résidence Cheikhoul Khadim', id: 32)
Rubrique.create(titre: 'La Source du Miséricorde Aïnou Rahmaty', id: 33)
